[package]
name = "solana-instruction"
description = "Types for directing the execution of Solana programs."
documentation = "https://docs.rs/solana-instruction"
version = "3.5.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["solana-instruction-v4/bincode"]
borsh = ["solana-instruction-v4/borsh"]
default = ["std"]
# The `frozen-abi` feature is unused. Remove with the next breaking release.
frozen-abi = ["solana-instruction-v4/frozen-abi"]
serde = ["solana-instruction-v4/serde"]
# The `std` feature is currently unused and retained for backwards compatibility.
std = ["solana-instruction-v4/std"]
syscalls = ["solana-instruction-v4/syscalls"]
wincode = ["solana-instruction-v4/wincode"]

[dependencies]
solana-instruction-v4 = { package = "solana-instruction", version = "4.0.0" }
solana-instruction-error = { workspace = true, features = ["num-traits"] }

[lints]
workspace = true
