//! This module extends `frozen-abi` with binary-level compatibility checks.

use {
    arbitrary::{Arbitrary, Unstructured},
    rand::RngCore,
};

/// Enables binary layout stability testing.
///
/// Types that implement this trait can be tested via `test_abi_digest` (generated by
/// the `#[frozen_abi(abi_digest = "...")]` attribute)
/// which is used to detect unintended changes in serialized representations.
///
/// Meant to be used with `#[derive(StableAbi)]` from `frozen-abi-macro`.
pub trait StableAbi: Sized {
    fn random(rng: &mut impl RngCore) -> Self
    where
        Self: for<'a> Arbitrary<'a>,
    {
        // NOTE: As bytes being consumed, it might lead to buffer exhaust.
        // In such case increase the `MAX_TYPE_SIZE` accordingly
        // keeping in mind that increasing this value has impact on frozen-abi tests runtime.
        const MAX_TYPE_SIZE: usize = 4096;

        let mut buffer = vec![0u8; MAX_TYPE_SIZE];
        rng.fill_bytes(&mut buffer);
        let mut unstructured = Unstructured::new(&buffer);

        Self::arbitrary(&mut unstructured).expect("failed to fill - try increasing MAX_TYPE_SIZE")
    }
}
