//! This module extends `frozen-abi` with binary-level compatibility checks.

use {
    arbitrary::{Arbitrary, Unstructured},
    rand::RngCore,
};

/// Enables binary layout stability testing.
///
/// Types that implement this trait can be tested via `test_abi_digest` (generated by
/// the `#[frozen_abi(abi_digest = "...")]` attribute)
/// which is used to detect unintended changes in serialized representations.
///
/// Meant to be used with `#[derive(StableAbi)]` from `frozen-abi-macro`.
pub trait StableAbi: Sized {
    fn random(rng: &mut impl RngCore) -> Self
    where
        Self: for<'a> Arbitrary<'a>,
    {
        const FALLBACK_SIZE: usize = 4096;
        const DEPTH: usize = 0;

        let (min, max) = Self::size_hint(DEPTH);
        let buffer_size = max.unwrap_or(FALLBACK_SIZE).max(min);

        let mut buffer = vec![0u8; buffer_size];
        rng.fill_bytes(&mut buffer);
        let mut unstructured = Unstructured::new(&buffer);

        Self::arbitrary(&mut unstructured).expect("failed to fill")
    }
}
